#RAD-2271 added bug fix and tests for upserting db system settings for new modules - 5.0.x
MangoAutomation/ma-core-public pull request #1842
Opened 2023-03-17 02:35 UTC by pierpuccini

This fixed the following: When a module is being installed for a first time, the systemAccessor class doesn’t have create capabilities.

More info at #[RAD-2271](https://radixiot.atlassian.net/browse/RAD-2271)

2023-03-17 16:34 UTC, terrypacker requested changes

2023-03-17 16:34 UTC, terrypacker commented on Core/src-test/com/serotonin/m2m2/db/dao/systemsettingsaccessor/SystemSettingsAccessorTest.java
> +    public void testInsertNewModules () {
This test could use some documentation, after what we did yesterday it isn't real obvious what this test does unless you add some comments.  Just write some javadoc above the method to explain why that assertion is there and what the test is doing.

2023-03-21 23:54 UTC, terrypacker approved these changes
Thanks

2023-03-22 15:28 UTC, benji811124 approved these changes

2023-03-22 17:02 UTC, merged